name: Publish Package to npmjs

on:
  push:
    branches:
      - main # 当推送到 main 分支时触发

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install
        
      - name: Bump version and publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          # 可选参数，用于配置版本号递增规则
          # 默认递增 patch 版本号
          bump-minor-pre-major: true # pre-major 版本优先递增 minor 版本号
          # 其他可选参数，例如 tag, access 等，请参考插件文档
          # https://github.com/JS-DevTools/npm-publish
